DROP TABLE IF EXISTS BOTTLE;

CREATE TABLE BOTTLE (
id INT AUTO_INCREMENT PRIMARY KEY,
name VARCHAR (250) NOT NULL,
bottlePic VARCHAR (250) NOT NULL,
volume FLOAT NOT NULL,
isAlcoholic BOOLEAN,
volumePercent FLOAT NOT NULL,
price INT (250),
supplier CHAR (250) NOT NULL,
inStock INT (250) NOT NULL
);